apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - issuer.yaml
  - secret.yaml

labels:
  - pairs:
      app.kubernetes.io/name: api-server
      app.kubernetes.io/part-of: marriott-application
      app.kubernetes.io/component: api