# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: api-server-secret
# type: Opaque
# stringData:
#   DB_URL: postgresql://user:password@db-host:5432/app
#   REDIS_URL: redis://:password@redis-host:6379/0
#   JWT_SECRET: change-me
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: ssm-secrets-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-2

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-credentials
spec:
  secretStoreRef:
    name: ssm-secrets-store
    kind: SecretStore
  dataFrom:
  - extract:
      # fake
      key: rds!cluster-e49ca894-12345-1234-1234-123412341234
      conversionStrategy: Default
      decodingStrategy: None
  refreshInterval: 1h
  target:
    name: db-credentials
    creationPolicy: Owner
    deletionPolicy: Retain  